format:
  html:
    template: resources/_templates/default.html  
    theme: none
    css: styles.css
    highlight-style: atom-one-dark
    toc: false
    page-layout: article
    code-fold: false

project:
  type: website
  output-dir: docs

website:
  title: "Nina's Notes"
  navbar:
    left:
      - text: Projects
        href: projects/index.qmd
      - text: Notes
        href: notes/index.qmd
    right:
      - text: Email
        href: "mailto:nixterra78@gmail.com"

  page-footer:
    left: "© 2025 Nina"
    right: "Built with [Quarto](https://quarto.org)"



