project:
  type: website
  output-dir: docs

website:
  title: "Nina's Notes"
  navbar:
    left:
      - text: Projects
        href: projects/index.qmd
      - text: About
        href: about.qmd

    right:
      - icon: moon
        href: "#"
        aria-label: "Toggle theme"

  page-footer:
    left: "© 2025 Nina"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: none
    template: resources/_templates/default.html
    css: styles.css
    highlight-style: atom-one-dark
    toc: false
    page-layout: full
    code-fold: false



