project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar: false  
  page-footer: false 

format:
  html:
    theme: null  
    css: styles.css
    toc: false
    page-layout: full  
    code-fold: false   



