project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar: false  
  page-footer: "" 

format:
  html:
    theme: none  
    highlight-style: atom-one-dark
    template: resources/_templates/default.html
    css: styles.css
    toc: false
    page-layout: full  
    code-fold: false
      



