project:
  type: website
  output-dir: docs

website:
  title: "Nina"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Notes
        href: notes/index.qmd
      - text: Contact
        href: contact.qmd

  page-footer:
    left: "© 2025 Nina"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: none
    template: resources/_templates/default.html
    css: styles.css
    highlight-style: atom-one-dark
    toc: false
    page-layout: full
    code-fold: false
      



