project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
          - text: "Medium Analysis"
            href: projects/medium-analysis.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



